### ISSUE TITLE
Error: Cannot find module 'babel-register'

### ISSUE THREAD

**Issue by dreamoftrees** [katallaxie/generator-i-want-nice-ng-cordova#1]
Had an issue generating my app with the error message about 'babel-register'.
A quick npm install -g babel-register sorted the issue.

You may want to update your setup to include babel-register.

Thanks for your work, looks like a great starting point.

**Comment by katallaxie** [comment]
Thx, I forgot to add this as local dependency. I will remove this altogether; as the idea actually were not to  compile the generator.
