### ISSUE TITLE
Unable to fetch "C:/development/angular/i-want-nice-ng-cordova/src/app/app.js". Only file URLs of the form file:/// allowed running in Node.

### ISSUE THREAD

**Issue by tobytraylor** [katallaxie/generator-i-want-nice-ng-cordova#6]
# Executing "Grunt Debug":

> Fatal error: Unable to fetch "C:/development/angular/i-want-nice-ng-cordova/src/app/app.js". Only file URLs of the form file:/// allowed running in Node.
# Running "Grunt Fun"

there are no errors from grunt but nothing renders and the browser console:

> http://localhost:8080/cordova.js  Failed to load resource: the server responded with a status of 404 (Not Found)
> http://localhost:8080/zone.js/lib/browser/zone-microtask.js Failed to load resource: the server responded with a status of 404 (Not Found)
> Error: XHR error (404 Not Found) loading http://localhost:8080/zone.js/lib/browser/zone-microtask.js(…)
> http://localhost:8080/reflect-metadata.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by katallaxie** [comment]
This seems to be an issue with the paths resolution on windows. I have to look into that.

**Comment by katallaxie** [comment]
Could you please pull the lastest version #8 and try again, thx.

**Comment by tobytraylor** [comment]
Lates version only throws the cordova.js error, which i take will be there while in desktop development mode regardless.  THough it throws this error during build

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--loglevel=error"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! juryVision@0.0.0 postinstall: `jspm install && grunt init`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the juryVision@0.0.0 postinstall script 'jspm install && grunt init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the juryVision package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install && grunt init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs juryVision
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls juryVision
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\angular\i-want-nice-ng-cordova-0.4.4\npm-debug.log

**Comment by tobytraylor** [comment]
Wait sorry, got so excited the runtime errors went away i forgot to run the build.  Still getting:
Fatal error: Unable to fetch "C:/development/angular/i-want-nice-ng-cordova-0.4.4/src/app/app.js". Only file URLs of the form file:/// allowed running in Node.
